### PR TITLE
Backported to 47.1.3

### PR DESCRIPTION
**Pull request by smifflepuss**

### CODE REVIEW

**Comment by Faboslav** [comment]
Why do we need this?

**Comment by smifflepuss** [comment]
Cause some mods like Sully's Mod Jade aren't compatible with 47.1.43 or higher. OK?

**Comment by Faboslav** [comment]
Then why dont you make PR for Sully's Mod to bump their forge version?

**Comment by smifflepuss** [comment]
Any version above 47.1.3 broke the jade block behavior for arrows, etc.

**Comment by Faboslav** [comment]
Then they should fix the error, forcing other mods to downgrade is not the correct way to resolve this issue.

**Comment by Faboslav** [comment]
There is plenty of errors fixed on the forge side between these two versions.

**Comment by smifflepuss** [comment]
You should accept that Urantepus said to us about Sully's Mod. OK?

**Comment by Faboslav** [comment]
I dont understand, what do you mean by that?

**Comment by Faboslav** [comment]
Are these https://github.com/Uraneptus/Sullys-Mod/issues/15 https://github.com/Uraneptus/Sullys-Mod/issues/48 related to your bug?

**Comment by smifflepuss** [comment]
Yes

**Comment by Faboslav** [comment]
These are one year old issues, force the author to do the proper fixes, not me to downgrade the forge version.

**Comment by smifflepuss** [comment]
Well, I don't have any other choice

**Comment by Faboslav** [comment]
> > Are these [Uraneptus/Sullys-Mod#15](https://github.com/Uraneptus/Sullys-Mod/issues/15) [Uraneptus/Sullys-Mod#48](https://github.com/Uraneptus/Sullys-Mod/issues/48) related to your bug?
> 
> Hi. The linked issue is not the problem. That's something different. The problem is that forge 47.1.4 brought a breaking change that made our system for the Jade blocks completely useless when using any Projectile that extends the AbstractArrow class. However we do not enforce using a version of forge below 47.1.4, because the mod is still playable on other version, since pretty much only arrows and tridents break with jade. And as it was already said, other mods should not be required to change their forge version range for other mods to be compatible with them, so I also consider this PR as not necessary!

Yeah, then it is settled, since i dropped forge support for 1.20.4+, i can at least check if i can downgrade the version to the mentioned one as one of the last changes on the forge side for me.

@smifflepuss It is possible, that, this will be merged with the next version of friends&foes, we will see.

**Comment by smifflepuss** [comment]
> > > Are these [Uraneptus/Sullys-Mod#15](https://github.com/Uraneptus/Sullys-Mod/issues/15) [Uraneptus/Sullys-Mod#48](https://github.com/Uraneptus/Sullys-Mod/issues/48) related to your bug?
> > 
> > 
> > Hi. The linked issue is not the problem. That's something different. The problem is that forge 47.1.4 brought a breaking change that made our system for the Jade blocks completely useless when using any Projectile that extends the AbstractArrow class. However we do not enforce using a version of forge below 47.1.4, because the mod is still playable on other version, since pretty much only arrows and tridents break with jade. And as it was already said, other mods should not be required to change their forge version range for other mods to be compatible with them, so I also consider this PR as not necessary!
> 
> Yeah, then it is settled, since i dropped forge support for 1.20.4+, i can at least check if i can downgrade the version to the mentioned one as one of the last changes on the forge side for me.
> 
> @smifflepuss It is possible, that, this will be merged with the next version of friends&foes, we will see.

Well let's port it to 47.1.3 then and see what happens.

**Comment by Uraneptus** [comment]
> > Are these [Uraneptus/Sullys-Mod#15](https://github.com/Uraneptus/Sullys-Mod/issues/15) [Uraneptus/Sullys-Mod#48](https://github.com/Uraneptus/Sullys-Mod/issues/48) related to your bug?
> 
> Hi. The linked issue is not the problem. That's something different. The problem is that forge 47.1.4 brought a breaking change that made our system for the Jade blocks completely useless when using any Projectile that extends the AbstractArrow class. However we do not enforce using a version of forge below 47.1.4, because the mod is still playable on other version, since pretty much only arrows and tridents break with jade. And as it was already said, other mods should not be required to change their forge version range for other mods to be compatible with them, so I also consider this PR as not necessary!

I found a way to handle this. I'm hoping to release a version soon that will work on version above and below 47.1.4!

**Comment by Faboslav** [comment]
That is good news, i am closing this in favor of the fix, but just in case i was able to lower the requirement(will be released with next update)

**Pull request closed without merging**
